#! /bin/bash

pip3 install pyflakes pep8 pylint ipython

git clone https://github.com/gmarik/Vundle.vim.git ~/.vim/bundle/Vundle.vim

git archive --remote=ssh://andysu/vim.git .vimrc | tar -xO /some/path/file.txt > ~/.vimrc2

