#! /bin/bash

pip3 install pyflakes pep8 pylint ipython

git clone https://github.com/gmarik/Vundle.vim.git ~/.vim/bundle/Vundle.vim

wget -O ~/.vimrc https://raw.githubusercontent.com/andysu/vim/refs/heads/main/.vimrc 
